import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "luca-naujoks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center bg-background w-screen h-screen max-h-screen px-12 pt-12 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-full bg-foreground rounded-t-xl bg-radial-[at_90%_10%] from-effect to-foreground to-35%">
          {children}
        </div>
      </body>
    </html>
  );
}
